package config

import (
	"bufio"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// SecretsFileName lives in ARKIVE_DATA_DIR so it is backed up (and restored)
// together with the blobs whose credentials it protects.
const SecretsFileName = ".arkive-secrets"

const (
	secretsKeySession = "ARKIVE_SESSION_SECRET"
	secretsKeyKey     = "ARKIVE_SECRETS_KEY"
)

// SecretsResult describes what ResolveSecrets did, for logging.
type SecretsResult struct {
	Path    string
	Used    bool // at least one value came from the file
	Created bool // the file was created or extended on this boot
	Adopted bool // SecretsKey came from adoptSecretsKey (1.0 upgrade)
}

// SecretsFilePath returns <DataDir>/.arkive-secrets.
func (c Config) SecretsFilePath() string {
	dir := strings.TrimSpace(c.DataDir)
	if dir == "" {
		dir = "/data/arkive"
	}
	return filepath.Join(dir, SecretsFileName)
}

// ResolveSecrets fills SessionSecret / SecretsKey that were not provided by the
// environment. Values persisted in <DataDir>/.arkive-secrets are reused;
// missing ones are generated (32 random bytes) and written back with mode 0600.
// Environment values always win and are never written to the file.
//
// adoptSecretsKey (optional) is consulted only when a secrets key must be
// created from scratch. A non-empty return is persisted instead of a random
// key — this keeps a 1.0 install that ran on the placeholder key able to
// decrypt its stored credentials after upgrading.
func (c *Config) ResolveSecrets(adoptSecretsKey func() string) (SecretsResult, error) {
	res := SecretsResult{Path: c.SecretsFilePath()}
	if c.SessionSecret != "" && c.SecretsKey != "" {
		return res, nil
	}

	stored, err := readSecretsFile(res.Path)
	if err != nil {
		return res, err
	}
	changed := false
	fill := func(dst *string, name string, gen func() (string, error)) error {
		if *dst != "" {
			return nil
		}
		if v := stored[name]; v != "" {
			*dst = v
			res.Used = true
			return nil
		}
		v, err := gen()
		if err != nil {
			return err
		}
		stored[name] = v
		*dst = v
		res.Used = true
		changed = true
		return nil
	}
	if err := fill(&c.SessionSecret, secretsKeySession, GenerateSecret); err != nil {
		return res, err
	}
	if err := fill(&c.SecretsKey, secretsKeyKey, func() (string, error) {
		if adoptSecretsKey != nil {
			if v := strings.TrimSpace(adoptSecretsKey()); v != "" {
				res.Adopted = true
				return v, nil
			}
		}
		return GenerateSecret()
	}); err != nil {
		return res, err
	}
	if changed {
		if err := writeSecretsFile(res.Path, stored); err != nil {
			return res, err
		}
		res.Created = true
	}
	return res, nil
}

// GenerateSecret returns 32 random bytes, base64url-encoded (43 chars).
func GenerateSecret() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generate secret: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

func readSecretsFile(path string) (map[string]string, error) {
	out := map[string]string{}
	f, err := os.Open(path)
	if errors.Is(err, fs.ErrNotExist) {
		return out, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		out[strings.TrimSpace(k)] = strings.TrimSpace(v)
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	return out, nil
}

func writeSecretsFile(path string, values map[string]string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}
	var b strings.Builder
	b.WriteString("# Generated by Arkive. Keep this file private and back it up with the data\n")
	b.WriteString("# directory: ARKIVE_SECRETS_KEY decrypts stored storage/SMTP/OAuth credentials.\n")
	b.WriteString("# Environment variables with the same names override these values.\n")
	for _, k := range []string{secretsKeySession, secretsKeyKey} {
		if v := values[k]; v != "" {
			fmt.Fprintf(&b, "%s=%s\n", k, v)
		}
	}
	tmp, err := os.CreateTemp(dir, SecretsFileName+".tmp-*")
	if err != nil {
		return fmt.Errorf("write secrets file: %w", err)
	}
	defer os.Remove(tmp.Name())
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return fmt.Errorf("write secrets file: %w", err)
	}
	if _, err := tmp.WriteString(b.String()); err != nil {
		tmp.Close()
		return fmt.Errorf("write secrets file: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("write secrets file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("write secrets file: %w", err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return fmt.Errorf("write secrets file: %w", err)
	}
	return nil
}
